
public class Main {

	public static void main(String[] args) {
		
		/* Problem 1: If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
		 *  The sum of these multiples is 23.
		 *  Find the sum of all the multiples of 3 or 5 below 1000 
		 */
		//initialize limit for problem 1
		int p1 = 1000;
		System.out.println("Problem 1: Sum of 3 or 5 divisible natural numbers less than " + p1);
		System.out.println("wait for it .. " + Problem1.calculate(p1));

		/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
		 * By starting with 1 and 2, the first 10 terms will be:
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
		 * find the sum of the even-valued terms.
		 */
		//initialize values for problem 2
		int p2 = 4000000;
		System.out.println("Problem 2: Sum of even Fibonacci terms not exceeding " + p2);
		System.out.println("wait for it .. " + Problem2.calculate(p2));

	}

}
